from __future__ import annotations

from pathlib import Path

import pytest

from tools.repo_checks import boundary_truth_check, module_size_check, reference_policy_check

pytestmark = pytest.mark.unit


def write_lines(path: Path, count: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("x = 1\n" * count, encoding="utf-8")


def test_module_size_check_accepts_small_modules(tmp_path: Path) -> None:
    write_lines(tmp_path / "src/open_postal_codes/example.py", 12)
    write_lines(tmp_path / "tests/unit/test_example.py", 12)
    write_lines(tmp_path / "tools/repo_checks/example_check.py", 12)

    assert module_size_check.validate_file_sizes(tmp_path) == []


def test_module_size_check_rejects_large_product_modules(tmp_path: Path) -> None:
    write_lines(
        tmp_path / "src/open_postal_codes/large.py",
        module_size_check.MAX_PRODUCT_LINES + 1,
    )

    errors = module_size_check.validate_file_sizes(tmp_path)

    assert errors == ["product module exceeds 850 lines: src/open_postal_codes/large.py (851)"]


def test_boundary_truth_check_accepts_current_layering(tmp_path: Path) -> None:
    source_root = tmp_path / "src/open_postal_codes"
    source_root.mkdir(parents=True)
    (source_root / "countries.py").write_text(
        "from __future__ import annotations\nimport re\nfrom dataclasses import dataclass\n",
        encoding="utf-8",
    )
    (source_root / "post_code.py").write_text(
        "from open_postal_codes.countries import DEFAULT_COUNTRY_CONFIG\n",
        encoding="utf-8",
    )
    (source_root / "refresh_data.py").write_text(
        "from open_postal_codes.post_code import PostCodeRecord\n",
        encoding="utf-8",
    )

    assert boundary_truth_check.validate_boundaries(source_root) == []


def test_boundary_truth_check_rejects_domain_importing_network_code(tmp_path: Path) -> None:
    source_root = tmp_path / "src/open_postal_codes"
    source_root.mkdir(parents=True)
    (source_root / "post_code.py").write_text("import urllib.request\n", encoding="utf-8")

    errors = boundary_truth_check.validate_boundaries(source_root)

    assert errors == [
        f"{(source_root / 'post_code.py').as_posix()}: domain model imports urllib.request"
    ]


def test_boundary_truth_check_rejects_orchestration_cycles(tmp_path: Path) -> None:
    source_root = tmp_path / "src/open_postal_codes"
    source_root.mkdir(parents=True)
    (source_root / "refresh_data.py").write_text(
        "from open_postal_codes.pages import package_pages\n",
        encoding="utf-8",
    )

    errors = boundary_truth_check.validate_boundaries(source_root)

    assert errors == [
        f"{(source_root / 'refresh_data.py').as_posix()}: "
        "orchestration module imports open_postal_codes.pages"
    ]


def test_reference_policy_rejects_public_provenance_terms(tmp_path: Path) -> None:
    path = tmp_path / "README.md"
    path.write_text("Generated by " + "Cod" + "ex\n", encoding="utf-8")

    assert reference_policy_check.reference_errors_for_path(path) == [
        f"{path}: contains prohibited reference"
    ]


def test_reference_policy_allows_normal_project_words(tmp_path: Path) -> None:
    path = tmp_path / "README.md"
    path.write_text("This API is maintained as public data.\n", encoding="utf-8")

    assert reference_policy_check.reference_errors_for_path(path) == []
